[project]
authors = ["Jesus Jayaro <jayaro@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "aer_parser"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.80.1,<2"
